const rokushoTheEnforcer = () => ({
  name: 'Rokusho the Enforcer',
  race: 'High Human',
  LVL: 250,
  ACC: 200,
  HEA: 350,
  STR: 100,
  WIS: 150,
  DEX: 150,
  INT: 150,
  DEF: 150,
  chance: 25,
  gear: {
    Head: 'helmetOfRokusho',
    Neck: 'amuletOfPity',
    Shoulders: 'shouldersOfEnforcement',
    Body: 'bodyOfEnforcement',
    Legs: 'legsOfEnforcement',
    Cape: 'battlewornCape',
    RightHand: 'bowOfDarkness',
    RightRing: 'ringOfEndurance',
    LeftRing: 'ringOfStability',
    Feet: 'bootsOfEnforcement',
  },
  drops: [
    { name: 'coin', amount: 1000, chance: 30 },
    { name: 'coin', amount: 2000, chance: 20 },
    { name: 'coin', amount: 3000, chance: 15 },
    { name: 'coin', amount: 4000, chance: 15 },
    { name: 'battlewornCape', amount: 1, chance: 10 },
    { name: 'bowOfDarkness', amount: 1, chance: 1 },
    { name: 'helmetOfRokusho', amount: 1, chance: 1 },
    { name: 'ringOfEndurance', amount: 1, chance: 1 },
    { name: 'ringOfStability', amount: 1, chance: 1 },
    { name: 'shouldersOfEnforcement', amount: 1, chance: 1 },
    { name: 'bodyOfEnforcement', amount: 1, chance: 1 },
    { name: 'legsOfEnforcement', amount: 1, chance: 1 },
    { name: 'bootsOfEnforcement', amount: 1, chance: 1 },
    { name: 'amuletOfPity', amount: 1, chance: 1 },
    { name: 'amuletOfDamnation', amount: 1, chance: 1 },
  ],
  experience: 45000,
});

const arundieleTheEnforcer = () => ({
  name: 'Arundiele',
  race: 'High Human',
  LVL: 150,
  ACC: 200,
  HEA: 250,
  STR: 150,
  WIS: 100,
  DEX: 150,
  INT: 100,
  DEF: 150,
  chance: 25,
  gear: {
    RightHand: 'bowOfDarkness',
    RightRing: 'ringOfEndurance',
    LeftRing: 'ringOfStability',
    Head: 'helmetOfArundiele',
    Shoulders: 'shouldersOfEnforcement',
    Body: 'bodyOfEnforcement',
    Legs: 'legsOfEnforcement',
    Feet: 'bootsOfEnforcement',
    Cape: 'battlewornCape',
    Neck: 'amuletOfPity',
  },
  drops: [
    { name: 'coin', amount: 1000, chance: 20 },
    { name: 'coin', amount: 2000, chance: 20 },
    { name: 'coin', amount: 3000, chance: 15 },
    { name: 'coin', amount: 4000, chance: 15 },
    { name: 'battlewornCape', amount: 1, chance: 10 },
    { name: 'bowOfDarkness', amount: 1, chance: 1 },
    { name: 'helmetOfArundiele', amount: 1, chance: 1 },
    { name: 'ringOfEndurance', amount: 1, chance: 1 },
    { name: 'ringOfStability', amount: 1, chance: 1 },
    { name: 'shouldersOfEnforcement', amount: 1, chance: 1 },
    { name: 'bodyOfEnforcement', amount: 1, chance: 1 },
    { name: 'legsOfEnforcement', amount: 1, chance: 1 },
    { name: 'bootsOfEnforcement', amount: 1, chance: 1 },
    { name: 'amuletOfPity', amount: 1, chance: 1 },
    { name: 'amuletOfDamnation', amount: 1, chance: 1 },
  ],
  experience: 45000,
});

module.exports = {
  rokushoTheEnforcer,
  arundieleTheEnforcer,
};
