module.exports = {
  HEAD: 'HEAD',
  NECK: 'NECK',
  SHOULDERS: 'SHOULDERS',
  BODY: 'BODY',
  LEGS: 'LEGS',
  CAPE: 'CAPE',
  LEFTHAND: 'LEFTHAND',
  LEFTRING: 'LEFTRING',
  RIGHTHAND: 'RIGHTHAND',
  RIGHTRING: 'RIGHTRING',
  FEET: 'FEET',
};