module.exports = {
  masteryThresholds: {
    10: { name: '[NAME] Tracker', STR: 5, INT: 5 },
    50: { name: '[NAME] Hound', WIS: 5, DEF: 5 },
    100: {
      name: '[NAME] Impaler',
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
    },
    500: {
      name: 'Adept Slayer of [NAME]',
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
    1000: {
      name: 'Slayer of [NAME]s',
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
    10000: {
      name: 'Master Slayer of [NAME]s',
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
    100000: {
      name: 'Grandmaster Slayer of [NAME]s',
      STR: 10,
      INT: 10,
      WIS: 10,
      DEF: 10,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
  },
};
