module.exports = {
  masteryThresholds: {
    10: { name: (name) => `${name} Tracker`, STR: 5, INT: 5 },
    50: { name: (name) => `${name} Hound`, WIS: 5, DEF: 5 },
    100: {
      name: (name) => `${name} Impaler`,
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
    },
    500: {
      name: (name) => `Adept Slayer of ${name}`,
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
    1000: {
      name: (name) => `Slayer of ${name}`,
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
    10000: {
      name: (name) => `Master Slayer of ${name}s`,
      STR: 5,
      INT: 5,
      WIS: 5,
      DEF: 5,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
    100000: {
      name: (name) => `Grandmaster Slayer of ${name}s`,
      STR: 10,
      INT: 10,
      WIS: 10,
      DEF: 10,
      ACC: 5,
      DEX: 5,
      SPD: 5,
    },
  },
};
